version: '3.3'

services:
    db:
        image: mysql:5.7
        container_name: ivelin_mysql
        environment:
            DOCKER_COMPOSE_YML_LOCATION: ${PWD}
        restart: always
        volumes:
            - ./backend/database/db.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database
            - db_data:/var/lib/mysql # persist database data inside docker storage
                
    phpmyadmin:
        container_name: ivelin_phpmyadmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            DOCKER_COMPOSE_YML_LOCATION: ${PWD}

    wordpress:
        container_name: ivelin_wordpress
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            DOCKER_COMPOSE_YML_LOCATION: ${PWD}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
        volumes:
            - ./backend/wp-content:/var/www/html/wp-content
    nextjs:
        container_name: ivelin_web
        depends_on:
            - db
            - wordpress
        environment: 
            WP_URL: http://wordpress
            WP_GRAPHQL: "index.php?graphql"
        ports:
            - "3001:3000"
        build:
            context: ./docker/web
            args:
                WP_URL: http://WORDPRESS_DB_HOST
                WP_PORT: "80"
    nginx:
        build: ./docker/nginx
        container_name: ivelin_nginx
        ports:
            - 80:80

volumes:
    db_data: {}