version: '3.3'

services:
    db:
        image: mysql:5.7
        container_name: ivelin_mysql
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            DOCKER_COMPOSE_YML_LOCATION: ${PWD}
        restart: always
        volumes:
            - ./backend/database/db.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database
            - db_data:/var/lib/mysql # persist database data inside docker storage

    phpmyadmin:
        container_name: ivelin_phpmyadmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            DOCKER_COMPOSE_YML_LOCATION: ${PWD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    wordpress:
        container_name: ivelin_wordpress
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            DOCKER_COMPOSE_YML_LOCATION: ${PWD}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
        volumes:
            - ./backend/wp-content:/var/www/html/wp-content

    nextjs:
        container_name: ivelin_web
        depends_on:
            - wordpress
        environment:
            WP_URL: wordpress
            WP_GRAPHQL: "index.php?graphql"
        ports:
            - "3001:3000"
        build:
            context: ./
            dockerfile: ./docker/web/Dockerfile
        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:3000"]
            interval: 5s
            timeout: 5s
            retries: 50
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
            args:
                WEB_URL: nextjs
        container_name: ivelin_nginx
        depends_on:
            nextjs:
                condition: service_healthy
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

volumes:
    db_data: {}