version: 2.1

jobs:
  deploy:
    docker:
    # specify the version you desire here (you might not want node)
    - image: circleci/node:7.10
    steps:
      - checkout 
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./run.sh”


# Orchestrate our job run sequence
workflows:
  deploy_to_server:
    jobs:
      - deploy